name: "sample react cd pipeline / workflow"

on:
    workflow run:
         workflow: ["sample react cd pipeline / workflow"]
         types:
            -completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:

            - name: "Setup Node.js"
              uses: actions/setup-node@v4
              with:
                node-version: '20'


            - name: "Setup Vercel cli"
              run: npm install -g vercel

            - name: "Download build files"
              uses: actions/download-artifact@v4
              with: 
                name: build
                run-id: ${{ github.event.workflow_run.id }}
                github-token : ${{github.token}}

            - name: "Deploy to Vercel"
              run: vercel --prod --token=${{secrets.VERCEL_TOKEN}} --confirm --name=cicdproject
              env:
                VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}